---
- name: Automatic Remediation of a webserver
  hosts: localhost
  sources:
    - name: ping web server
      url_check:
        urls:
          - http://localhost:5000
        delay: 1
    - name: process check
      process_check:
    - name: file facts
      file:
        files:
        - fact.yml
  rules:
    - name: If webserver is down remediate the problem
      condition:
        all:
          - facts.process_pid << fact.pid is defined
          - events.url_down << event.url_check.status == "down"
          - events.process_down << event.process_check.pid == facts.process_pid.pid and event.process_check.status == "stopped"
      action:
        run_playbook:
          name: start_app.yml
          copy_files: true
          post_events: true

...
